[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "yaqd_thorlabs"
dist-name = "yaqd-thorlabs"
author = "yaq Developers"
author-email = "git@ksunden.space"
home-page = "https://yaq.fyi"
description-file = "README.md"
requires-python = ">=3.7"
requires = ["yaqd-core>=2020.10.1",
            "thorlabs-apt-protocol>=29.0.0",
	    "pyserial",
	    "pyvisa",
	    "pyvisa-py",
	    "pyusb"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Topic :: Scientific/Engineering",
]

[tool.flit.metadata.urls]
Source = "https://github.com/yaq-project/yaqd-thorlabs"
Issues = "https://github.com/yaq-project/yaqd-thorlabs/issues"

[tool.flit.metadata.requires-extra]
dev = ["black", "pre-commit"]

[tool.flit.scripts]
yaqd-thorlabs-bsc201="yaqd_thorlabs._thorlabs_bsc201:ThorlabsBSC201.main"
yaqd-thorlabs-bsc203="yaqd_thorlabs._thorlabs_bsc203:ThorlabsBSC203.main"
yaqd-thorlabs-ell18="yaqd_thorlabs._thorlabs_ell18:ThorlabsEll18.main"
yaqd-thorlabs-k10cr1="yaqd_thorlabs._thorlabs_k10cr1:ThorlabsK10CR1.main"
yaqd-thorlabs-kdc101="yaqd_thorlabs._thorlabs_kdc101:ThorlabsKDC101.main"
yaqd-thorlabs-kst101="yaqd_thorlabs._thorlabs_kst101:ThorlabsKST101.main"
yaqd-thorlabs-lts150="yaqd_thorlabs._thorlabs_lts150:ThorlabsLTS150.main"
yaqd-thorlabs-lts300="yaqd_thorlabs._thorlabs_lts300:ThorlabsLTS300.main"
yaqd-thorlabs-mpc320="yaqd_thorlabs._thorlabs_mpc320:ThorlabsMPC320.main"
yaqd-thorlabs-pax1000="yaqd_thorlabs._thorlabs_pax1000:ThorlabsPAX1000.main"
yaqd-thorlabs-pm-triggered="yaqd_thorlabs._thorlabs_pm_triggered:ThorlabsPMTriggered.main"

[tool.black]
line-length = 99
target-version = ['py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | build
  | dist
)/
'''
