protocol = "thorlabs-ellx"
doc = ""
traits = ["has-transformed-position", "has-limits", "is-homeable", "uses-uart", "is-daemon"]
hardware = ["thorlabs:ell18", "thorlabs:ell18m", "thorlabs:ell14"]

[links]
source = "https://github.com/yaq-project/yaqd-thorlabs"
bugtracker = "https://github.com/yaq-project/yaqd-thorlabs/-/issues"
manufacturer = "https://www.thorlabs.com/search/thorsearch.cfm?search=elliptec"

[installation]
PyPI = "https://pypi.org/project/yaqd-thorlabs"

[config]
address.type = "int"
address.default = 0
address.doc = "Address for ELLx messages (default 0)"

scalar.type = "double"
scalar.default = 398
scalar.doc = "Conversion factor from motor steps to units"

units.type = "string"
units.default = "deg"

baud_rate.default = 9600
make.default = "Thorlabs"
model.default = "ellx"

[state]
status.type = "string"
status.doc = "Device status, translated into text from the get status (gs) command."
status.default = ""
